export const Role = [
  { label: "Frontend Developer", value: "Frontend Developer" },
  { label: "Backend Developer", value: "Backend Developer" },
  { label: "Management", value: "Management" },
  { label: "DevOps", value: "DevOps" },
  { label: "Quality Assurance", value: "Quality Assurance" },
  { label: "Analytics", value: "Analytics" },
  { label: "Software Development", value: "Software Development" },
  { label: "Human Resources", value: "Human Resources" },
  { label: "Design", value: "Design" },
  { label: "Agile Management", value: "Agile Management" },
  { label: "Cloud Services", value: "Cloud Services" },
  { label: "Database Management", value: "Database Management" },
  { label: "Product Management", value: "Product Management" },
  { label: "Cybersecurity", value: "Cybersecurity" },
];
