export const TaskList = [
  {
    id: 1,
    title: "Optimize Database Queries",
    date: "2024-08-31",
    priority: "low",
    stage: "in_progress",
    assets: 4,
    activities: 10,
    subTasks: 1,
    team: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        role: "Backend Engineer",
      },
      {
        name: "Alice Smith",
        email: "alice.smith@example.com",
        role: "Database Administrator",
      },
      {
        name: "Robert Johnson",
        email: "robert.johnson@example.com",
        role: "DevOps Engineer",
      },
      {
        name: "Michael Brown",
        email: "michael.brown@example.com",
        role: "Software Engineer",
      },
      {
        name: "Sophia White",
        email: "sophia.white@example.com",
        role: "QA Engineer",
      },
    ],
  },
  {
    id: 2,
    title: "Bug Fixing in Backend",
    date: "2024-09-20",
    priority: "low",
    stage: "todo",
    assets: 6,
    activities: 6,
    subTasks: 9,
    team: [
      {
        name: "David Wilson",
        email: "david.wilson@example.com",
        role: "Backend Developer",
      },
    ],
  },
  {
    id: 3,
    title: "Improve Performance",
    date: "2024-09-26",
    priority: "high",
    stage: "in_progress",
    assets: 1,
    activities: 2,
    subTasks: 1,
    team: [
      {
        name: "Ethan Brown",
        email: "ethan.brown@example.com",
        role: "Software Engineer",
      },
      {
        name: "Isabella Davis",
        email: "isabella.davis@example.com",
        role: "Performance Analyst",
      },
      {
        name: "Lucas Miller",
        email: "lucas.miller@example.com",
        role: "Backend Engineer",
      },
      {
        name: "Emma Johnson",
        email: "emma.johnson@example.com",
        role: "Frontend Developer",
      },
    ],
  },
  {
    id: 4,
    title: "Design RESTful Services",
    date: "2024-09-08",
    priority: "high",
    stage: "completed",
    assets: 5,
    activities: 10,
    subTasks: 3,
    team: [
      {
        name: "Liam Wilson",
        email: "liam.wilson@example.com",
        role: "API Developer",
      },
      {
        name: "Ava Taylor",
        email: "ava.taylor@example.com",
        role: "System Architect",
      },
      {
        name: "James Thomas",
        email: "james.thomas@example.com",
        role: "Backend Developer",
      },
    ],
  },
  {
    id: 5,
    title: "Write Documentation",
    date: "2024-09-16",
    priority: "medium",
    stage: "in_progress",
    assets: 4,
    activities: 9,
    subTasks: 5,
    team: [
      {
        name: "Sophia Martinez",
        email: "sophia.martinez@example.com",
        role: "Technical Writer",
      },
      {
        name: "Olivia White",
        email: "olivia.white@example.com",
        role: "Documentation Specialist",
      },
      {
        name: "Mason Lewis",
        email: "mason.lewis@example.com",
        role: "Project Manager",
      },
    ],
  },
  {
    id: 6,
    title: "Improve Performance",
    date: "2024-08-31",
    priority: "medium",
    stage: "in_progress",
    assets: 10,
    activities: 5,
    subTasks: 5,
    team: [
      {
        name: "Liam Walker",
        email: "liam.walker@example.com",
        role: "Performance Engineer",
      },
      {
        name: "Mia Harris",
        email: "mia.harris@example.com",
        role: "System Analyst",
      },
      {
        name: "Lucas Allen",
        email: "lucas.allen@example.com",
        role: "Backend Developer",
      },
      {
        name: "Ella Young",
        email: "ella.young@example.com",
        role: "Frontend Developer",
      },
      {
        name: "Noah King",
        email: "noah.king@example.com",
        role: "QA Engineer",
      },
    ],
  },
  {
    id: 7,
    title: "Update Dependencies",
    date: "2024-09-20",
    priority: "low",
    stage: "todo",
    assets: 2,
    activities: 4,
    subTasks: 7,
    team: [
      {
        name: "Amelia Scott",
        email: "amelia.scott@example.com",
        role: "DevOps Engineer",
      },
      {
        name: "Henry Clark",
        email: "henry.clark@example.com",
        role: "Software Engineer",
      },
      {
        name: "Evelyn Lewis",
        email: "evelyn.lewis@example.com",
        role: "Release Manager",
      },
      {
        name: "Benjamin Adams",
        email: "benjamin.adams@example.com",
        role: "Backend Developer",
      },
    ],
  },
  {
    id: 8,
    title: "Create Unit Tests",
    date: "2024-09-15",
    priority: "high",
    stage: "completed",
    assets: 7,
    activities: 7,
    subTasks: 9,
    team: [
      {
        name: "Charlotte Clark",
        email: "charlotte.clark@example.com",
        role: "Test Engineer",
      },
      { name: "Jack Moore", email: "jack.moore@example.com", role: "QA Lead" },
    ],
  },
  {
    id: 9,
    title: "Security Patch",
    date: "2024-09-10",
    priority: "normal",
    stage: "todo",
    assets: 3,
    activities: 5,
    subTasks: 2,
    team: [
      {
        name: "Harper Parker",
        email: "harper.parker@example.com",
        role: "Security Analyst",
      },
      {
        name: "Mason Rivera",
        email: "mason.rivera@example.com",
        role: "DevOps Engineer",
      },
      {
        name: "Aiden Wright",
        email: "aiden.wright@example.com",
        role: "Backend Developer",
      },
    ],
  },
  {
    id: 10,
    title: "Setup CI/CD Pipeline",
    date: "2024-09-12",
    priority: "medium",
    stage: "in_progress",
    assets: 6,
    activities: 6,
    subTasks: 5,
    team: [
      {
        name: "William Hill",
        email: "william.hill@example.com",
        role: "DevOps Engineer",
      },
      {
        name: "Emma Young",
        email: "emma.young@example.com",
        role: "Software Developer",
      },
      {
        name: "Daniel Green",
        email: "daniel.green@example.com",
        role: "CI/CD Specialist",
      },
      {
        name: "Grace Hall",
        email: "grace.hall@example.com",
        role: "Infrastructure Engineer",
      },
    ],
  },
];
