export const TeamMemberList = [
  {
    name: "Emily Johnson",
    designation: "Software Engineer",
    email: "emily.johnson@example.com",
    role: "Frontend Developer",
    status: "Active",
  },
  {
    name: "Michael Smith",
    designation: "Senior Software Engineer",
    email: "michael.smith@example.com",
    role: "Backend Developer",
    status: "Active",
  },
  {
    name: "Sophia Williams",
    designation: "Project Manager",
    email: "sophia.williams@example.com",
    role: "Management",
    status: "Inactive",
  },
  {
    name: "Liam Brown",
    designation: "DevOps Engineer",
    email: "liam.brown@example.com",
    role: "DevOps",
    status: "Active",
  },
  {
    name: "Olivia Davis",
    designation: "QA Engineer",
    email: "olivia.davis@example.com",
    role: "Quality Assurance",
    status: "Active",
  },
  {
    name: "William Wilson",
    designation: "Lead Software Architect",
    email: "william.wilson@example.com",
    role: "Architect",
    status: "Active",
  },
  {
    name: "Mason Martinez",
    designation: "Technical Lead",
    email: "mason.martinez@example.com",
    role: "Management",
    status: "Inactive",
  },
  {
    name: "Ava Taylor",
    designation: "Data Analyst",
    email: "ava.taylor@example.com",
    role: "Analytics",
    status: "Active",
  },
  {
    name: "James Anderson",
    designation: "Full Stack Developer",
    email: "james.anderson@example.com",
    role: "Software Development",
    status: "Active",
  },
  {
    name: "Charlotte Lee",
    designation: "HR Manager",
    email: "charlotte.lee@example.com",
    role: "Human Resources",
    status: "Inactive",
  },
  {
    name: "Benjamin Walker",
    designation: "System Administrator",
    email: "benjamin.walker@example.com",
    role: "Infrastructure",
    status: "Active",
  },
  {
    name: "Mia Harris",
    designation: "UI/UX Designer",
    email: "mia.harris@example.com",
    role: "Design",
    status: "Active",
  },
  {
    name: "Ethan Clark",
    designation: "Scrum Master",
    email: "ethan.clark@example.com",
    role: "Agile Management",
    status: "Active",
  },
  {
    name: "Isabella Wright",
    designation: "Cloud Engineer",
    email: "isabella.wright@example.com",
    role: "Cloud Services",
    status: "Inactive",
  },
  {
    name: "Lucas Thompson",
    designation: "Database Administrator",
    email: "lucas.thompson@example.com",
    role: "Database Management",
    status: "Active",
  },
  {
    name: "Emma White",
    designation: "Chief Technology Officer",
    email: "emma.white@example.com",
    role: "Executive Management",
    status: "Active",
  },
  {
    name: "Noah Lewis",
    designation: "Network Engineer",
    email: "noah.lewis@example.com",
    role: "Networking",
    status: "Inactive",
  },
  {
    name: "Amelia Young",
    designation: "Product Manager",
    email: "amelia.young@example.com",
    role: "Product Management",
    status: "Active",
  },
  {
    name: "Logan King",
    designation: "Mobile App Developer",
    email: "logan.king@example.com",
    role: "Software Development",
    status: "Inactive",
  },
  {
    name: "Harper Scott",
    designation: "Security Analyst",
    email: "harper.scott@example.com",
    role: "Cybersecurity",
    status: "Active",
  },
];
